### ISSUE TITLE
Set up Semaphore CI integration

### ISSUE THREAD

**Issue by lmb** [newtools/ebpf#14]
libbcc seems to use Semaphore CI with a custom stage1 to run eBPF unit tests. We can probably do the same.

**Comment by lmb** [comment]
I've created kinvolk/stage1-builder#30 to update the kernels of the test runner to the latest versions.

@nathanjsweet can you please sign up to semaphoreci.com and let me know your username, so I can add you to the org? You also have to authorize semaphore CI to access this repo, seems like I don't have enough permissions do to that.

Assigning to you for the time being.

**Comment by lmb** [comment]
Yeah, it needs some custom setup to run the tests in a VM. I've added you 
as an owner of the new tools org, can you add the ebpf repo to it?

**Comment by lmb** [comment]
Bump, could you take a look?

**Comment by nathanjsweet** [comment]
@lmb I'm trying to get this working, but I'm having trouble I think I made a good start here:
https://github.com/newtools/ebpf/blob/semaphore/semaphore.sh

But I'm getting `rkt` errors that, from my perusal of rkt issues, appear to be related to kernel version.
The project is integrated with semaphore ci now, so you should be able to fiddle with the `semaphore` branch.

**Comment by nathanjsweet** [comment]
I'll take another crack at it later this week.
