### ISSUE TITLE
Remove pointer to Instructions

### ISSUE THREAD

**Issue by nathanjsweet** [newtools/ebpf#17]
on behalf of @lmb 
Get rid of *Instructions since it is equivalent to *[]BPFInstruction and pointers to slices usually aren't necessary (need to double check that)

**Comment by nathanjsweet** [comment]
The only problem I see with this are these two functions:
https://github.com/newtools/ebpf/blob/master/types.go#L1103
https://github.com/newtools/ebpf/blob/master/types.go#L1109

**Comment by lmb** [comment]
Sorry, I should have been more specific. Instructions is fine, but *Instructions doesn't make much sense imo.

So:
```
type Instructions []BPFInstruction (or just [] Instruction?)

func NewProg(ins Instructions) ...
```

**Comment by nathanjsweet** [comment]
Seems like you're right. I thought the whole slice got passed, but it's just the header:
https://forum.golangbridge.org/t/slice-pass-as-value-or-pointer/2866/2

**Comment by nathanjsweet** [comment]
Done.
