### ISSUE TITLE
Make *Spec Types Real Types instead of Interfaces

### ISSUE THREAD

**Issue by nathanjsweet** [newtools/ebpf#18]
on behalf of @lmb 
Make *Spec regular structs instead of interfaces, and make GetELFSections return a "list of specs" (CollectionSpec? not sure). This will allow users to load from ELF, but then tweak the programs if they desire.

**Comment by nathanjsweet** [comment]
As I said in #20 I don't know if making them structs buys us that much other than letting library users do relocating themselves. I think we could solve that by having a parse parameter that delays relocation, and a method on the specs that allow them to specify different relocation parameters, then initiate relocation (it already is based on symbol name anyways).

As far as having a "list of specs". I think that's a good idea, the two argument thing is awkward, and we could probably put the higher level relocation functionality on that.

**Comment by lmb** [comment]
Maybe you're right, and I'm missing something that requires an interface. I usually reach for an interface if I want to enable multiple implementations of something, which doesn't seem so apply to the *Spec.
What functionality does the interface give us?

**Comment by nathanjsweet** [comment]
Nah, you're right. I think I had an early version of the code needing interfaces, but the elf refactor I did got rid of the need. We can get rid of the interfaces.
