### ISSUE TITLE
Make Relo Functionality More Generic

### ISSUE THREAD

**Issue by nathanjsweet** [newtools/ebpf#20]
on behalf of @lmb 
Make the map instruction replacement mechanism more generic, so that e.g. constants could be swapped in at runtime. (Might be enough to parse more symbols from ELF)

**Comment by nathanjsweet** [comment]
I think this relates to #18 somewhat. From my perspective this is the one that we need to make easier. Otherwise I don't know what #18 gets us other than this (please correct me if I'm wrong).

**Comment by lmb** [comment]
I have a branch with some working code for this. I learned just recently that its also possible to have real function calls in BPF, so I need to check that the code works with that.
