### ISSUE TITLE
proposal: add layer of abstraction between assembler and BPF bit stream format

### ISSUE THREAD

**Issue by lmb** [newtools/ebpf#23]
The approach in #22  works well when parsing a program from an ELF, but it's cumbersome to use when assembling a program using the DSL.

e.g. from TestRewriteUint64:
```Go
	ins := Instructions{
		BPFILdImm64(Reg0, 0),
		BPFIOp(Exit),
	}

	spec := &ProgramSpec{
		XDP,
		ins,
		"MIT",
		0,
		map[string][]*BPFInstruction{
			"ret": []*BPFInstruction{ins[0]}, // <---- this part
		},
	}

	spec.RewriteUint64("ret", 42)

	prog, err := NewProgram(spec)
	if err != nil {
		t.Fatal(err)
	}
	defer prog.Close()
```

For this use case it would be nicer to attach labels / symbols to specific instructions, rather than having to manually create the map[str][]*BPFInstruction. BPFInstruction already has sectionName, but that isn't exposed to users of the API. I also noticed that it's not possible to compare BPFInstruction loaded from an ELF file and the return value of e.g. BPFIDstSrc. I think this is due to *extra being different in these cases. The mechanism to convert Instructions via bpfInstruction and unsafe to a byte array is also a bit hacky imo.

I'd like to propose the following:
* Make BPFInstruction the logical representation of a BPF instruction, meaning it can store full 64bit values without the extra field.
* Add a MarshalBinary function to Instructions which serialises BPFInstruction to []byte
* Make BPFI* functions return a private type asmStatement (open to a better name)
* Add a function `func Assemble([]asmStatement) *ProgramSpec`
* Add a function `func (asmStatement) Symbol(string) asmStatement`
* (Optional, but good idea IMO) move assembly related functions to sub-package ebpf/asm and drop BPF* prefix in names

The above code would then become:
```Go
	spec := asm.Assemble(&ProgramSpec{
		Type: XDP,
		License: "MIT",
	}, []asm.Instruction{
		asm.LdImm64(Reg0, 0).Reference("ret"),
		asm.Op(Exit),
	})

	// All references to "ret" will be overridden with 42
	spec.RewriteUint64("ret", 42)

	prog, err := NewProgram(spec)
	if err != nil {
		t.Fatal(err)
	}
	defer prog.Close()
```

As a bonus, we'd be able to compare instructions parsed from ELF and the result of asm.* functions, which is useful in unit tests.

**Comment by lmb** [comment]
Thoughts @nathanjsweet ?

**Comment by nathanjsweet** [comment]
I'm not sure I fully understand the `Symbol` method, can you elaborate on it?

**Comment by lmb** [comment]
Yes, I realised that `Symbol` is a bad name, `Reference` is better. It allows you to declare a reference to a symbol. Multiple instructions with the same opcode can reference the same symbol. After calling `Assemble` it's then possible to rewrite all references with a specific value. Once we add more rewrite functions this could also work for function calls, etc.

**Comment by nathanjsweet** [comment]
okay, I get it.

**Comment by nathanjsweet** [comment]
This is done now, right?

**Comment by lmb** [comment]
I'm still thinking about moving assembly into a sub package, but the 
important bits are done.
