### ISSUE TITLE
BPF instructions offsets are wrong

### ISSUE THREAD

**Issue by majek** [newtools/ebpf#3]
I think load mapfd instruction takes two opcodes, while ebpf printout shows only one

from ebpf lib printout 
```
10: op: LdImmDW dst: r1 imm: 5  # r1 = mapfd
        ex-10-1: op: LdImmW dst: r0 imm: 0
11: op: Call MapLookupElement # mapLookupelement(r1=mapfd, r2=fp-4= pointer to value of r0)
```
From kernel message
```
        10: (18) r1 = 0x0
        12: (85) call bpf_map_lookup_elem#1
```
Notice - kernel doesn't show instruction \#11.

**Comment by majek** [comment]
Specifically the `r1 = 0x0` seem to take two words.

**Comment by lmb** [comment]
The second word is encoded as `ex-10-1: op: LdImmW dst: r0 imm: 0`. That's an artifact of how instructions are encoded in the package and can be improved.
