### ISSUE TITLE
Array rewriting breaks if array is accessed multiple times

### ISSUE THREAD

**Issue by arthurfabre** [newtools/ebpf#55]
When global arrays are accessed multiple times consecutively, llvm does not re-emit a LOAD, DEREF instruction pair, it reuses the register that was previously LOAD'd into. The current implementation rewrites LOADs to actually load the constant, and the DEREFs to MOV the constant from the register it was LOAD'd into. Multiple access to an array cause the same value (or whatever is left in the original register) to be used.

A fix can be found here: https://github.com/arthurfabre/ebpf/commit/d3b783d3bf1b6ff1f24ba2187d1c1eeed2b597c5

We haven't benchmarked the performance hit of using maps instead of array rewriting yet, but if it's low it may not be worth having to constantly fudge the output of clang - ideally global rewriting would be something that would be supported by clang (eg by generating a single instruction for each access). This could also avoid wasting a register.

**Comment by lmb** [comment]
We ended up removing array rewriting. It's possible to emulate this using a predictable naming scheme to an extent.
